apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskflow.fullname" . }}-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ include "taskflow.name" . }}-api